#!/bin/bash
#
# ./composer - Acesso ao composer dockerizado 
#
# Este programa executa comandos do composer que está localizado dentro do conteiner
# docker, dispensando a necessidade de instalar o composer no computador local

PHP_CONTAINER='freep-console'

docker-compose up -d

docker exec -it $PHP_CONTAINER \
    composer $@